### ISSUE TITLE
Celestial ring/signet

### ISSUE THREAD

**Issue by SlayerElder** [botanicvelious/Equipment-Inspector#16]
Celestial ring and Celestial signet uncharged and charged versions don't show up.

**Comment by botanicvelious** [comment]
items all come from runelite, not sure why they wouldnt work

**Comment by pwatts6060** [comment]
Ammuniton / Ring slot data isn't sent from server to client as it doesn't affect appearance so isn't necessary to be sent. There is no way to know that information afaik.

**Comment by Waistcoat** [comment]
Closing as impossible
