### ISSUE TITLE
[Suggestion] show member items with a different color name

### ISSUE THREAD

**Issue by AVellucci** [botanicvelious/Equipment-Inspector#18]
currently when inspecting players in F2P worlds (yeah I don't pay for RS) Member items just show up with the name "Member's Object"
Would be nice to actually get the item name and instead show it in red, or pink or some other colour (user-customizable maybe) and that way a free player would still know what the item is
<img width="238" alt="RuneLite_-_Fatr3d" src="https://user-images.githubusercontent.com/11682773/169634374-ebb358a0-4bee-47a9-a532-f5c88db8b3a2.png">

**Comment by Waistcoat** [comment]
made a change to add a little worldswitcher-style members icon/star after members items for this. Jagex already kinda fixed it by adding (Members) after members items but hope you like my change. gonna close the issue since Jagex technically addressed it. feel free to submit more suggestions
