### ISSUE TITLE
Doesn't work for head slot items

### ISSUE THREAD

**Issue by sean-duffy** [botanicvelious/Equipment-Inspector#2]
![image](https://user-images.githubusercontent.com/2118422/74754849-293b8900-526a-11ea-9869-055ca9d04748.png)
![image](https://user-images.githubusercontent.com/2118422/74754903-3d7f8600-526a-11ea-8963-13cb6e61712e.png)

Unsure what is causing this at the moment.

**Comment by botanicvelious** [comment]
there is a bug in runelite, it has been fixed for next release
