### ISSUE TITLE
Error <img=20> when used alongside Ground Items plugin

### ISSUE THREAD

**Issue by BarbarianpriestessAki** [botanicvelious/Equipment-Inspector#22]
![image](https://github.com/botanicvelious/Equipment-Inspector/assets/136507359/84e9be38-c425-49a5-aaa4-1ce92fa90053)
this issue keeps happening whenever both plugins are in use. I'm not sure what's causing the conflict however.

**Comment by Waistcoat** [comment]
This is an incompatibility between F2P Highlight and Ground Items, you should open an issue here if you need this to be addressed

https://github.com/Mark7625/runelite-external-plugins/issues

or you can disable F2P highlight
