### ISSUE TITLE
Hide side bar icon when not in use

### ISSUE THREAD

**Issue by Gollum69** [botanicvelious/Equipment-Inspector#26]
The icon is permanently shown on the sidebar, and with the evergrowing list of plugins adding icons on that sidebar it makes it really difficult to manage them. Going through my icons I saw this plugin but it's never actually used, only when you right click someone and press Equipment on them. It would be nice if the icon is hidden until you press Equipment on a player and then it reappears while you're looking at their equipment. 
Thank you

**Comment by Waistcoat** [comment]
submitted https://github.com/runelite/plugin-hub/pull/5393

**Comment by Waistcoat** [comment]
merged
