### ISSUE TITLE
Equipment drop down is shown twice

### ISSUE THREAD

**Issue by xperiaclash** [botanicvelious/Equipment-Inspector#36]
Example as follows, seems to have happened after the latest runelite update.
Runelite version : 1.10.20.2
Launcher version : 2.6.10
![image](https://github.com/botanicvelious/Equipment-Inspector/assets/37775694/90607c22-f1dd-45f2-b715-78fb998aa63b)

**Comment by Waistcoat** [comment]
This is already fixed, just waiting to be merged https://github.com/runelite/plugin-hub/pull/5395
