### ISSUE TITLE
Equipment Inspector not working

### ISSUE THREAD

**Issue by VKMax24** [botanicvelious/Equipment-Inspector#42]
Right clicking on a player no longer shows the option to view their equipment. I've tried toggling the "hold shift" option as well as uninstalling and reinstalling the plugin itself, but it's still not working. I think this started a week or two ago. I'm using RuneLite version 2.6.4 through the official Jagex launcher.

This plugin is one of my favorites so any and all help is appreciated!

**Comment by Waistcoat** [comment]
@VKMax24 There is a known bug in a previous version that would cause this. Did you restart the client? I'm not sure that the plugin version would be updated just by reinstalling the plugin itself (counterintuitive but kinda how software works sometimes). If that doesn't work, you can download your runelite profile via wrench->profile bot dudes->default->export, then upload here so I can take a closer look.

Also this plugin will conflict with other plugins that add "player options" (you can't currently have more than 7 maximum player options including trade, follow, highscores lookup, and equipment).

**Comment by VKMax24** [comment]
@Waistcoat The "player options" thing was the problem! I had "right-click 'predict' players" toggled for the bot detector. Thank you so much!!
